//connect
export const CONNECTION_REQUEST = "CONNECTION_REQUEST";
export const INIT_CONTRACT_SUCCESS = "INIT_CONTRACT_SUCCESS";
export const CHECK_NETWORK_DONE = "CHECK_NETWORK_DONE";
export const CONNECTION_FAILED = "CONNECTION_FAILED";
export const METAMASK_CONNECTION_FAILED = "METAMASK_CONNECTION_FAILED";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_NETWORK = "UPDATE_NETWORK";

//contract data
export const CONTRACT_DATA_REQUEST = "CONTRACT_DATA_REQUEST";
export const CONTRACT_DATA_SUCCESS = "CONTRACT_DATA_SUCCESS";
export const ACCOUNT_DATA_SUCCESS = "ACCOUNT_DATA_SUCCESS";
export const CONTRACT_DATA_FAILED = "CONTRACT_DATA_FAILED";

export const CONTRACT_EXTRA_DATA_SUCCESS = "CONTRACT_EXTRA_DATA_SUCCESS";
export const ACCOUNT_EXTRA_DATA_SUCCESS = "ACCOUNT_EXTRA_DATA_SUCCESS";


//contract transaction
export const CONTRACT_TRANSACTION_REQUEST = "CONTRACT_TRANSACTION_REQUEST";
export const CONTRACT_TRANSACTION_SUCCESS = "CONTRACT_TRANSACTION_SUCCESS";
export const CONTRACT_TRANSACTION_FAILED = "CONTRACT_TRANSACTION_FAILED";
export const CHECK_TRANSACTION_PENDING = "CHECK_TRANSACTION_PENDING";
